# Generated by Django 5.2.17 on 2026-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BANK', 'Bank Transfer')], default='COD', max_length=10),
        ),
    ]
